<a href="https://colab.research.google.com/github/alexmora7/Laboratorio1_Alm_datos/blob/main/Laboratorio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ALEXANDER MORALES RESTREPO

Gestion y Almacenamiento de Datos

LABORATORIO 1 (NUMPY y PANDAS)

importamos las librerias

In [ ]:
import numpy as np
import pandas as pd

1. Resolver con numpy los siguientes casos:

1.1 Crea un vector de números enteros del 1 al 20.

In [ ]:
vector = np.arange (1,21) # creaer un vector del 1al 20
print (vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

1.2 Crea una matriz de 3x3 con valores aleatorios entre 0 y 1

In [ ]:
matriz = np.random.random ((3, 3)) # crear una matriz 3x3 con valores aleatorios entre o
print (matriz)

[[0.10329466 0.99705071 0.47761554]
 [0.32661859 0.14542616 0.0287034 ]
 [0.39970379 0.47373831 0.4689701 ]]

1.3 Redimensiona una matriz de 4x4 a una matriz de 2x8.

In [ ]:
matriz = np.random.randint (0,100, (4,4))
print (matriz)
##redimensionar a una matriz 2x8##
print (matriz.reshape (2,8))

[[57 70  6  1]
 [58 56 43 92]
 [ 4 40 87 31]
 [69 66 53 11]]
[[57 70  6  1 58 56 43 92]
 [ 4 40 87 31 69 66 53 11]]

1.4 Crea un array de 10 números equidistantes entre 0 y 1.

In [ ]:
vector = np.linspace (0,1,10)
print (vector)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

1.5 Concatena dos vectores vertical y horizontalmente. (concatenate)

In [ ]:
VectorA = np.arange (1,11)
VectorB = np.arange (11,21)

print (np.concatenate ((VectorA, VectorB), axis=0)) ## concatenar de manera horizontal
print (np.vstack((VectorA, VectorB))) ##concatenar de manera vertical

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

2. Resolver las siguientes operaciones:

2.1 Calcula la suma, resta, multiplicación y división de dos vectores.

In [ ]:
VectorA = np.arange (1,5)
VectorB = np.arange (5,9)
print (VectorA + VectorB) ## suma de 2 vectores
print (VectorA - VectorB) ## Resta de 2 Vectores
print (VectorA * VectorB) ## multiplicacion de 2 vectores
print (VectorA / VectorB) ## division de 2 vectores

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]

2.2 Calcula la media, mediana y desviación estándar de un vector.

In [ ]:
VectorA = np.arange (1,50)
print (np.mean (VectorA)) ## media de un vector
print (np.median (VectorA)) ## mediana de un vector
print (np.std (VectorA)) ## desviacion estandar de un vector

25.0
25.0
14.142135623730951

2.3 Normaliza un vector dividiendo cada elemento por el valor máximo.

In [ ]:
VectorA = np.arange (1,20)
print (VectorA / np.max (VectorA))

[0.05263158 0.10526316 0.15789474 0.21052632 0.26315789 0.31578947
 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737 0.63157895
 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684 0.94736842
 1.        ]

2.4 Encuentra el índice del valor máximo y mínimo en un vector.

In [ ]:
VectorA = np.arange (1,20)
print (np.argmax (VectorA)) ## indice del valor maximo
print (np.argmin (VectorA)) ## indice del valor minimo

18
0

2.5 Realiza una multiplicación matricial entre dos matrices 3x3.

In [ ]:
matrizA = np.random.randint (0,20, (3,3)) # crear una matriz 3x3 con valores variables
matrizB = np.random.randint (0,20, (3,3)) # crear una matriz 3x3 con valores variables
print (matrizA)
print (matrizB)
print (np.dot (matrizA, matrizB)) ## multiplicacion de 2 matrices

[[ 4 15  7]
 [15  0 19]
 [16  4 16]]
[[ 6  9  5]
 [ 9 19 19]
 [ 8 12 11]]
[[215 405 382]
 [242 363 284]
 [260 412 332]]

3. Resolver con numpy los siguientes casos:

3.1 Selecciona los elementos pares de un vector de números enteros

In [ ]:
VectorA = np.arange (1,20) ## crear el vector de 1 a 19
print (VectorA[VectorA % 2 == 0]) ## crear el vector A solo con numeros pares.

[ 2  4  6  8 10 12 14 16 18]

3.2 Filtra los valores mayores que 5 en un vector

In [ ]:
VectorA = np.arange (1,20) ## crear el vector de 1 a 19
print (VectorA[VectorA > 5]) ## crear el vector A solo con numeros mayores a 5.

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]

3.3 Filtra los valores iguales a cero

In [ ]:
VectorA = np.arange (0,20) ## crear el vector de 0 a 19
print (VectorA[VectorA == 0]) ## crear el vector A solo con numeros iguales a 0.

[0]

3.4 Filtra los valores negativos

In [ ]:
VectorA = np.arange (-10,20) ## crear el vector desde -10 hasta 19
print (VectorA[VectorA < 0 ]) # Crea un vector con solo los numeros negativos del vectorA

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]

3.5 Aplicar la media a los valores mayores de 50.

In [ ]:
VectorA = np.arange (20,100) ## crear el vector desde -10 hasta 19
print (np.mean (VectorA[VectorA > 50])) # Generar la media con ños numeros mayores a 50

75.0

4. Resolver con numpy los siguientes casos:

4.1 Crea un vector de 10 elementos y reemplaza todos los valores mayores
que 5 con 0

In [ ]:
VectorA = np.arange (0,10) ## crear el vector desde con 10 elementos
VectorA[VectorA > 5] = 0 ## Reemplazar los valores mayores a 5 por 0
print (VectorA)

[0 1 2 3 4 5 0 0 0 0]

4.2 Combina dos vectores booleanos utilizando las operaciones & (AND) y |
(OR).

In [ ]:
vectorA = np.array ([True, True, False, False])
vectorB = np.array ([False, False, True, True])
print (np.logical_and (vectorA, vectorB)) ## AND
print (np.logical_or (vectorA, vectorB)) ## OR

[False False False False]
[ True  True  True  True]

4.3 Cuenta la cantidad de valores en un vector que son múltiplos de 3

In [ ]:
VectorA = np.arange (20,100)
print (VectorA[VectorA % 3 == 0]) ## crea el vector A numeros multiplos de 3
print (len(VectorA[VectorA % 3 == 0])) ## cuenta la cantidad de numeros multiplos de 3

[21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90
 93 96 99]
27

4.4 Encuentra los índices de los elementos no nulos en un vector. (np.nonzero)

In [ ]:
vector = np.array([0, 1, 2, 3, 4, 0, 5, 0, 6, 0, 7, 8, 0, 9]) # Crear un vector con algunos elementos nulos (cero)
Posiciones= np.nonzero(vector) # encontrar las posiciones no nulas del vector creado
print(Posiciones)

(array([ 1,  2,  3,  4,  6,  8, 10, 11, 13]),)

4.5 Comprueba si todos los elementos en un array son mayores que un valor
específico digitado por el usuario

In [ ]:
vector = np.array([10, 15, 20, 25, 30])

valor = float(input("Introduce un valor: ")) # Solicitar un valor al usuario

mayores = np.all(vector > valor) # Comprueba si todos los elementos del array son mayores que el valor ingresado

if mayores:
    print(f"los elementos del array son mayores que {valor}.")
else:
    print(f" los elementos del array son manores que {valor}.")

Introduce un valor: 50
 los elementos del array son manores que 50.0.

5. Resolver con numpy los siguientes casos

5.1 Calcula el cuadrado de cada elemento en un vector

In [ ]:
VectorA = np.arange (0,10) ## crear el vector con 10 elementos
print (VectorA) ## generamos el vector
print (VectorA ** 2) ## elevamos al cuadrado cada elemento

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]

5.2 Utiliza la función exponencial para elevar todos los elementos de un vector
a la misma potencia.

In [ ]:
VectorA = np.arange (0,10) ## crear el vector con 10 elementos
print (VectorA) ## generamos el vector
print (np.exp(VectorA)) ## elevamos a la misma potencia

[0 1 2 3 4 5 6 7 8 9]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]

5.3 Encuentra los valores máximos y mínimos en cada fila de una matriz

In [ ]:
matriz = np.random.randint (0,100, (4,4)) ## crear una matriz 4x4 con valores variables
maximos = np.max(matriz, axis=1) ## Buscamos los valoeres maximos en la matriz creada
minimos = np.min(matriz, axis=1) ## Buscamos los valoeres minimos en la matriz creada
print (matriz)
print("Valor máximos en cada fila:", maximos)
print("Valor mínimos en cada fila:", minimos)

[[37 66 32 65]
 [43 83 33 57]
 [24 90 89 94]
 [47 62 65  7]]
Valor máximos en cada fila: [66 83 94 65]
Valor mínimos en cada fila: [32 33 24  7]

5.4 Aplica la función sin a todos los elementos de un vector y almacena los
resultados en otro vector

In [ ]:
VectorA = np.arange (0,10) ## creamos el vector con 10 elementos
print (VectorA)
print (np.sin(VectorA)) ## aplicamos la funcion sin a todos los elementos del vector

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]

5.5 Realiza la transpuesta de una matriz 3x4

In [ ]:
matriz =np.random.randint (0,100, (3,4)) ## crear una matriz 3x4 con valores variables
print (matriz)
print (matriz.T) ## Realizamos la transpuesta de la matriz

[[84 78 59 16]
 [96 73 72 16]
 [56 40 11 53]]
[[84 96 56]
 [78 73 40]
 [59 72 11]
 [16 16 53]]

6. Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'.
Añade al menos 10 registros.

In [ ]:
datos = { "Nombre": ["Alexander Morales","Diego Restrepo","Juan Calderon","Alberto Plazas","Ricardo Arjona","Luis Posada","Jaime Lopez","Jorge Ballesteros",
                    "Daniel MArtinez","Diana Gaviria"],
        "Edad": [30, 25, 50, 28, 36, 21, 23, 29, 20, 34],
        "Ciudad": ["Turin", "Barcelona", "Tokio", "Londres", "Roma", "Barcelona", "Lisboa", "Paris", "Liverpool", "Turin"]
        }
Usuarios = pd.DataFrame(datos)
Usuarios

              Nombre  Edad     Ciudad
0  Alexander Morales    30      Turin
1     Diego Restrepo    25  Barcelona
2      Juan Calderon    50      Tokio
3     Alberto Plazas    28    Londres
4     Ricardo Arjona    36       Roma
5        Luis Posada    21  Barcelona
6        Jaime Lopez    23     Lisboa
7  Jorge Ballesteros    29      Paris
8    Daniel MArtinez    20  Liverpool
9      Diana Gaviria    34      Turin

6.1 Del DataFrame creado, filtra a las personas que tienen más de 25 años.

In [ ]:
Usuarios [Usuarios ["Edad"] > 25 ]## filtramos a las personas que tienen mas de 25 años

              Nombre  Edad   Ciudad
0  Alexander Morales    30    Turin
2      Juan Calderon    50    Tokio
3     Alberto Plazas    28  Londres
4     Ricardo Arjona    36     Roma
7  Jorge Ballesteros    29    Paris
9      Diana Gaviria    34    Turin

6.2 A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellénala
con cualquier valor

In [ ]:
Usuarios ["Ingresos"] = [2500000, 2000000, 3000000, 2000000, 1500000, 2500000, 1500000, 1200000, 2000000, 1500000] ## creamos una nueva columna al Dataframe
Usuarios

              Nombre  Edad     Ciudad  Ingresos
0  Alexander Morales    30      Turin   2500000
1     Diego Restrepo    25  Barcelona   2000000
2      Juan Calderon    50      Tokio   3000000
3     Alberto Plazas    28    Londres   2000000
4     Ricardo Arjona    36       Roma   1500000
5        Luis Posada    21  Barcelona   2500000
6        Jaime Lopez    23     Lisboa   1500000
7  Jorge Ballesteros    29      Paris   1200000
8    Daniel MArtinez    20  Liverpool   2000000
9      Diana Gaviria    34      Turin   1500000

6.3 Encuentra el promedio de la edad en tu DataFrame

In [ ]:
Usuarios ["Edad"].mean() ## Encuentra el promedio de la edad

29.6

6.4 Cuenta cuántas veces aparece cada ciudad en tu DataFrame

In [ ]:
Usuarios ["Ciudad"].value_counts() ## Cuenta cuantas veces aparece cada ciudad

Ciudad
Turin        2
Barcelona    2
Tokio        1
Londres      1
Roma         1
Lisboa       1
Paris        1
Liverpool    1
Name: count, dtype: int64

6.5 Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para
cada ciudad. (groupby) →Investigarla

In [ ]:
Usuarios.groupby("Ciudad")["Edad"].mean() ## Agrupamos por ciudad y calcula el promedio de la edad

Ciudad
Barcelona    23.0
Lisboa       23.0
Liverpool    20.0
Londres      28.0
Paris        29.0
Roma         36.0
Tokio        50.0
Turin        32.0
Name: Edad, dtype: float64

6.6 Ordena tu DataFrame por 'Edad', de manera ascendente y luego
descendente

In [ ]:
Usuarios.sort_values("Edad") ## Organizamos por edad de manera ascendente

              Nombre  Edad     Ciudad  Ingresos
8    Daniel MArtinez    20  Liverpool   2000000
5        Luis Posada    21  Barcelona   2500000
6        Jaime Lopez    23     Lisboa   1500000
1     Diego Restrepo    25  Barcelona   2000000
3     Alberto Plazas    28    Londres   2000000
7  Jorge Ballesteros    29      Paris   1200000
0  Alexander Morales    30      Turin   2500000
9      Diana Gaviria    34      Turin   1500000
4     Ricardo Arjona    36       Roma   1500000
2      Juan Calderon    50      Tokio   3000000

In [ ]:
Usuarios.sort_values("Edad", ascending=False) ## Organizamos por edad de manera descendente

              Nombre  Edad     Ciudad  Ingresos
2      Juan Calderon    50      Tokio   3000000
4     Ricardo Arjona    36       Roma   1500000
9      Diana Gaviria    34      Turin   1500000
0  Alexander Morales    30      Turin   2500000
7  Jorge Ballesteros    29      Paris   1200000
3     Alberto Plazas    28    Londres   2000000
1     Diego Restrepo    25  Barcelona   2000000
6        Jaime Lopez    23     Lisboa   1500000
5        Luis Posada    21  Barcelona   2500000
8    Daniel MArtinez    20  Liverpool   2000000

7, Limpiar y preparar el dataset Clientes_Colombia.xlsx para su uso en análisis de
datos. Este laboratorio te ayudará a aplicar diversas técnicas de limpieza de datos
con pandas, incluyendo la gestión de valores faltantes, la eliminación de
duplicados, la normalización de formatos, el manejo de valores atípicos y la
conversión de tipos de datos. Este laboratorio te permitirá desarrollar habilidades
prácticas en la limpieza de datos utilizando pandas. Asegúrate de seguir cada
paso cuidadosamente y justificar cada decisión que tomes durante el proceso. Un
conjunto de datos limpio es fundamental para garantizar la precisión y eficacia de
cualquier análisis posterior

In [ ]:
## leemos el archivo externo
Datos_clientes = pd.read_excel("/content/Clientes_Colombia.xlsx")
Datos_clientes

,Nombre,Apellido,Fecha,ValorDeCompra (mil),Sucursal,Fechas_Diversas
0,teresa,DIAZ,02/01/2024,$60 COP,Cúcuta,01/04/2024
1,Antonio,ALONSO,05/01/2024,$420 COP,Barranquilla,07-01-2024
2,laura,Rubio,05/01/2024,$30 COP,Manizales,5 Jan 2024
3,PEDRO,DIAZ,06/01/2024,$440 COP,Cúcuta,2024/01/05
4,laura,Rubio,05/01/2024,$30 COP,Manizales,5 Jan 2024
...,...,...,...,...,...,...
9995,miguel,CASTILLO,01/01/2024,$180 COP,Cartagena,2024/01/05
9996,paula,Hernández,05/01/2024,$330 COP,Barranquilla,2024-01-07
9997,BEATRIZ,OrTIZ,01/01/2024,$20 COP,Cali,5 Jan 2024
9998,FERNANDO,MORENO,02/01/2024,$270 COP,Bogotá,01/04/2024
9999,Carlos,DIAZ,06/01/2024,$180 COP,Bogotá,2024/01/05

In [ ]:
Datos_clientes.info ()  ## revisamos el tipo de informacion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nombre               9925 non-null   object
 1   Apellido             9847 non-null   object
 2   Fecha                9904 non-null   object
 3   ValorDeCompra (mil)  9998 non-null   object
 4   Sucursal             9863 non-null   object
 5   Fechas_Diversas      10000 non-null  object
dtypes: object(6)
memory usage: 468.9+ KB

In [ ]:
Datos_clientes.isnull().sum() ##identificamos datos faltantes

Nombre                  75
Apellido               153
Fecha                   96
ValorDeCompra (mil)      2
Sucursal               137
Fechas_Diversas          0
dtype: int64

In [ ]:
Datos_clientes["Nombre"] = Datos_clientes["Nombre"].str.strip().str.title()### Limpiamos la columna de  Nombre y apellidos quitando espacios y organizando
Datos_clientes["Apellido"] = Datos_clientes["Apellido"].str.strip().str.title()
Datos_clientes.head(4) ## observamos las primeras 4 columnas para vizualizar el df

,Nombre,Apellido,Fecha,ValorDeCompra (mil),Sucursal,Fechas_Diversas
0,Teresa,Diaz,02/01/2024,$60 COP,Cúcuta,01/04/2024
1,Antonio,Alonso,05/01/2024,$420 COP,Barranquilla,07-01-2024
2,Laura,Rubio,05/01/2024,$30 COP,Manizales,5 Jan 2024
3,Pedro,Diaz,06/01/2024,$440 COP,Cúcuta,2024/01/05

In [ ]:
Datos_clientes['ValorDeCompra (mil)'] = Datos_clientes['ValorDeCompra (mil)'].str.replace(r'[^\d]', '', regex=True) ##Limpiamo la columna retirando el moneda y simbolo
Datos_clientes['ValorDeCompra (mil)'] = pd.to_numeric(Datos_clientes['ValorDeCompra (mil)'], errors='coerce').fillna(0).astype(int)  ##Convertir a enteros. Primero a float para manejar posibles NaN
Datos_clientes.head(4)

,Nombre,Apellido,Fecha,ValorDeCompra (mil),Sucursal,Fechas_Diversas
0,Teresa,Diaz,02/01/2024,60,Cúcuta,01/04/2024
1,Antonio,Alonso,05/01/2024,420,Barranquilla,07-01-2024
2,Laura,Rubio,05/01/2024,30,Manizales,5 Jan 2024
3,Pedro,Diaz,06/01/2024,440,Cúcuta,2024/01/05

In [ ]:
## Reliazamos un trabajo de limpieza sobre nuestro df
Datos_clientes['Fechas_Diversas'] = pd.to_datetime(Datos_clientes['Fechas_Diversas'], errors='coerce', dayfirst=True) ### Convertir  columnas fechas y fechas diversas  a formato de fecha
Datos_clientes['Fecha'] = pd.to_datetime(Datos_clientes['Fecha'], dayfirst=True)
Datos_clientes['Fecha'] = Datos_clientes['Fecha'].interpolate() ### Interpolacion de datos para agregar infomraicon en datos vacios
Datos_clientes['Fechas_Diversas'] = Datos_clientes['Fechas_Diversas'].fillna(Datos_clientes['Fecha']) ### Reemplazamos los Datos que salen en NAN de la columna Fechas diversas con el valoñr de la columna Fechas
Datos_clientes['Fechas_Diversas'] = Datos_clientes['Fechas_Diversas'].dt.strftime('%Y-%m-%d') # estanadarizamo la columan fecha diversas
Datos_clientes['Fechas_Diversas'].fillna('Valor_Predeterminado', inplace=True)
Datos_clientes['Nombre'].replace('', 'desconocido', inplace=True) ## llenamos los espacion vacion de la colimna nombre con la palabra Desconocidos
Datos_clientes['Nombre'].fillna('desconocido', inplace=True) ## eveluamos tambien los datos nulos
Datos_clientes['Apellido'].fillna('desconocido', inplace=True) ## llenamos los espacion vacion de la colimna Apellido con la palabra Desconocidos
Datos_clientes = Datos_clientes.drop_duplicates() ## Eliminamos los duplicados
Datos_clientes

,Nombre,Apellido,Fecha,ValorDeCompra (mil),Sucursal,Fechas_Diversas
0,Teresa,Diaz,2024-01-02 00:00:00,60,Cúcuta,2024-04-01
1,Antonio,Alonso,2024-01-05 00:00:00,420,Barranquilla,2024-01-05
2,Laura,Rubio,2024-01-05 00:00:00,30,Manizales,2024-01-05
3,Pedro,Diaz,2024-01-06 00:00:00,440,Cúcuta,2024-01-06
5,Sofia,Diaz,2024-01-01 00:00:00,180,Cúcuta,2024-01-01
...,...,...,...,...,...,...
4818,José,Álvarez,2024-01-05 00:00:00,490,Barranquilla,2024-01-05
6856,José,Álvarez,2024-01-06 00:00:00,490,Barranquilla,2024-01-06
8947,Antonio,Romero,2024-01-06 08:00:00,280,Medellín,2024-01-06
8948,José,Álvarez,2024-01-05 16:00:00,490,Barranquilla,2024-01-05
9482,Antonio,Romero,2024-01-03 00:00:00,280,Medellín,2024-01-03

In [ ]:
Datos_clientes.isnull().sum() ##identificamos datos faltantes

Nombre                 0
Apellido               0
Fecha                  0
ValorDeCompra (mil)    0
Sucursal               3
Fechas_Diversas        0
dtype: int64